Document: conman
Title: Debian conman Manual
Author: <insert document author here>
Abstract: This manual describes what conman is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/conman/conman.sgml.gz

Format: postscript
Files: /usr/share/doc/conman/conman.ps.gz

Format: text
Files: /usr/share/doc/conman/conman.text.gz

Format: HTML
Index: /usr/share/doc/conman/html/index.html
Files: /usr/share/doc/conman/html/*.html
